name: jonnyh
version: '0.2.0.0'

description: See README

author: Ludvig Sundström

maintainer: lud.sund@gmail.com

copyright: 2018 Ludvig Sundström

license: BSD3

github: lsund/jonnyh

extra-source-files:
- ChangeLog.md
- README.md

dependencies:
- base >=4.7 && <5
- protolude
- split
- text
- containers
- postgresql-simple
- pgn-parser
- HUnit
- extra
- random

default-extensions:
    - NoImplicitPrelude
    - OverloadedStrings

library:
  source-dirs: src

executables:
  jonnyh:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jonnyh
tests:
  jonnyh-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jonnyh
