name: chess-haskell
version: '0.1.0.0'

description: Please see the README on Github at <https://github.com/githubuser/chess-haskell#readme>

author: Author name here

maintainer: example@example.com

copyright: 2018 Author name here

license: BSD3

github: githubuser/chess-haskell

extra-source-files:
- ChangeLog.md
- README.md

dependencies:
- base >=4.7 && <5
- protolude
- split
- text
- containers
- parsec
- postgresql-simple

default-extensions:
    - NoImplicitPrelude
    - OverloadedStrings

library:
  source-dirs: src

executables:
  chess-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chess-haskell

tests:
  chess-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chess-haskell
